### ISSUE TITLE
sqrt(0) returns Maths error

### ISSUE THREAD

**Issue by carloshm** [James-Livesey/atto#16]
I expected sqrt(0) to return 0
10 print sqrt(0)
run
Maths error

**Comment by James-Livesey** [comment]
Good catch! I've updated the domain of `sqrt` in commit https://github.com/James-Livesey/atto/commit/71ac2a159e06761027b1c5156502e60a77f3306b. Thanks for spotting that!

**Comment by carloshm** [comment]
How frequently you deploy on https://jamesl.me/atto/? I use it as the test server :)

**Comment by James-Livesey** [comment]
[jamesl.me/atto](https://jamesl.me/atto) is actually a GitHub Pages site, which automatically pulls the latest version from the `main` branch every time there's a new commit. It looks like it's deployed the bug fix for this issue according to the [activity log](https://github.com/James-Livesey/atto/deployments/activity_log?environment=github-pages), though there is a small chance that GitHub Pages fails to deploy (and I have to make an empty commit to get it to redeploy).

It might be handy for you to hard-refresh the page at your end if you don't appear to have the most recent version of atto — on Chrome, it's normally done by pressing <kbd>Ctrl</kbd> + <kbd>F5</kbd> (or go into DevTools with <kbd>F12</kbd>, then right-click the browser's refresh button to see the option there). I think it's the same shortcut for Firefox, too. Seems to have all worked for me after hard refreshing, and I can now use `sqrt(0)` on the main site!

If you want to test stuff locally (and checkout non-main branches), feel free to clone the repo! You can then run a simple HTTP server and visit localhost to see atto there. I normally use Python's built-in server which seems to do the trick:

```bash
$ python3 -m http.server
```

Thanks for stress-testing atto, though! Glad to see that people are tesing out the language so that I can ensure that features generally work as expected.

**Comment by carloshm** [comment]
I really love the font and basic experience (bring some memories!). Hope I can share some more feedback and examples! nice work

**Comment by James-Livesey** [comment]
Ah, thanks! I definitely wanted that nice, friendly feel you get from beginners' languages such as Scratch, with all of the bright colours that appeal to younger programmers (in addition to the lovely Brass Mono font). At the same time, I also wanted the maturity of BASIC and its success in teaching programming — so that's how atto was born!

The whole project seems to be a success so far, and I'm glad that people are enjoying both using atto, but also the nostalgia. Also glad to see contributions to the project from the community, too.

Hopefully, we can get learners to use the language hands-on! Currently looking into that. Would be nice to see an atto workshop at some point when COVID is gone 😊
